project:
  type: website

website:
  title: "Data Party : Les 30 ans de la MTD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - idees_dataviz.qmd
      - href: visu_dataparty.qmd
        text: Visu faite pendant la data party
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



